-- 

WITH RECURSIVE GENERATION 
AS (
    -- 부모 아이디가 없으면 1세대로 초기화
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    -- 재귀 실행
    SELECT E.ID, E.PARENT_ID, GEN + 1
    FROM ECOLI_DATA AS E
    JOIN GENERATION AS G
    ON E.PARENT_ID = G.ID    
)

SELECT ID FROM GENERATION WHERE GEN = 3;