WITH CHILD_CNT AS (
    SELECT
        PARENT_ID ,
        COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT 
    ID,
    IFNULL(C.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E 
LEFT JOIN CHILD_CNT AS C
ON E.ID = C.PARENT_ID
ORDER BY ID;