WITH MAX_EMP AS (
    SELECT
        HG.EMP_NO,
        SUM(HG.SCORE) AS SCORE
    FROM HR_EMPLOYEES AS HE
    JOIN HR_GRADE AS HG
    ON HE.EMP_NO = HG.EMP_NO
    GROUP BY HG.EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
)


SELECT 
    MAX_EMP.SCORE,
    HE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM HR_EMPLOYEES AS HE
INNER JOIN MAX_EMP
ON HE.EMP_NO = MAX_EMP.EMP_NO;