-- 가격이 제일 비싼 식품의 분류, 가격, 이름
WITH RANK_TABLE AS (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, 
           RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKS
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM RANK_TABLE
WHERE RANKS = 1
ORDER BY MAX_PRICE DESC;
